### ISSUE TITLE
Update IDs of each of the types

### ISSUE THREAD

**Issue by kiwicopple** [supabase/pg-api#19]
In `src/lib/interfaces` we have all the different types of data we are returning. All of them are using "named" IDs. For example, tables has a field like `table_id` == `public.users`. This is prone to breakages if the user updates the name of the table or schema. 

We should add an `id` field to each of these which refers to PG's internal ID

**Comment by soedirgo** [comment]
I tried looking over our SQL templates, and here's what I found (in parentheses are the system tables to which the OIDs belong, if any):

Has OID:
- constraints (pg_constraint)
- extensions_enabled (pg_extension)
- roles (pg_roles)
- schemas (pg_namespace)
- sequences (pg_class)
- tables (pg_class)
- types (pg_type)
- views (pg_class)
- primary_keys (pg_constraint)

Has no OID:
- columns (pg_attribute)
- extensions (installed only: extensions_enabled)
- policies (pg_policy)

Not sure:
- grants (complicated, see below)
- relationships (seems like FK constraints? (pg_constraint))

Not applicable?
- config
- joins
- replication_temp
- table_size
- version

As for grants, I tried to look deeper into the SO threads and the docs mentioned in #18, and from my understanding, this doesn't show all privileges, e.g. if I never do a `GRANT` on a table, the privileges given will be `NULL`, which I'm guessing means default privilege, whatever that is. Also, the OID given is on the relation (the table), not the grants.

So for the permissions in `/project/[ref]/database/tables`, I think it's better to rely on the `has_table_privilege` function (where do expose this? `Tables.Table`? `Roles.Role`?) to get a "truthful" permission table.

**Comment by kiwicopple** [comment]
This is mostly done, and we can kaizen our way through the rest. Great job bobbie
