### ISSUE TITLE
Ability to fetch schema

### ISSUE THREAD

**Issue by kiwicopple** [supabase/pg-api#23]
A user should have the ability to `GET` the `/schemas` endpoint and receive back all the schemas in the Postgres database

**Comment by kiwicopple** [comment]
This one is important for Auth, as I need to split out some of the functions into a separate schema. Also useful for the change we're making to Extensions - enabling/disabling them all in a separate schema

**Comment by soedirgo** [comment]
Isn't this already implemented? https://supabase.github.io/pg-api/#pg-api-schemas

**Comment by kiwicopple** [comment]
My favourite type of issues are already solved
