### ISSUE TITLE
perf: optimise /tables route

### ISSUE THREAD

**Issue by kiwicopple** [supabase/pg-api#41]
It's proving extremely slow in prod. I assume the `with` joins are running sequentially and will need to be converted to regular joins

**Comment by kiwicopple** [comment]
Running tests, second pass:

![image](https://user-images.githubusercontent.com/10214025/88867636-a539f400-d240-11ea-9511-a9057337cd08.png)

running perf tests on the code:

![image](https://user-images.githubusercontent.com/10214025/88868334-7fadea00-d242-11ea-8861-ef5e1199c216.png)

**Comment by kiwicopple** [comment]
The quickest win that we can do here is to convert all the CTE's to [materialized](https://www.depesz.com/2019/02/19/waiting-for-postgresql-12-allow-user-control-of-cte-materialization-and-change-the-default-behavior/) CTE's:

![image](https://user-images.githubusercontent.com/10214025/88871852-783f0e80-d24b-11ea-8de5-4c0ab503fa1b.png)

![image](https://user-images.githubusercontent.com/10214025/88871862-7e34ef80-d24b-11ea-97ab-550a033a5396.png)


As we can see this has reduced the query by roughly a factor of 5. The caveat here is that the `MATERIALIZED` keyword for CTE's was only introduced in PG12 (and I don't think there is backwards compatibility), so we may have to look into alternative methods if we want to support older Postgres versions.

Lastly, our queries in general can probably be better. We are optimizing for development speed here, but in the future we may want to do a thorough optimization

**Comment by soedirgo** [comment]
I think this is mostly because we are `JOIN`ing `information_schema` views with system tables, e.g.:

```sql
-- tables.sql
...
FROM
  information_schema.tables
  JOIN pg_class c ON quote_ident(table_schema)::regnamespace = c.relnamespace
  AND c.relname = table_name
  LEFT JOIN pg_stat_user_tables ON pg_stat_user_tables.schemaname = tables.table_schema
  AND pg_stat_user_tables.relname = tables.table_name
...
```

`information_schema` views already use system tables under the hood (like below), so we could inline it, though it'd make the SQL templates pretty ugly.

```sql
-- information_schema.tables
...
FROM pg_namespace nc
  JOIN pg_class c ON nc.oid = c.relnamespace
  LEFT JOIN (pg_type t
  JOIN pg_namespace nt ON t.typnamespace = nt.oid) ON c.reloftype = t.oid
...
```

The performance difference is big though (10x):

```
# Not inlined
❯ hyperfine 'curl -s http://localhost:1337/tables' --warmup 5
Benchmark #1: curl -s http://localhost:1337/tables
  Time (mean ± σ):      1.004 s ±  0.027 s    [User: 4.3 ms, System: 5.5 ms]
  Range (min … max):    0.983 s …  1.063 s    10 runs

# Inlined
❯ hyperfine 'curl -s http://localhost:1337/tables' --warmup 5
Benchmark #1: curl -s http://localhost:1337/tables
  Time (mean ± σ):      97.6 ms ±   5.3 ms    [User: 4.2 ms, System: 5.1 ms]
  Range (min … max):    91.9 ms … 110.0 ms    27 runs
```

**Comment by kiwicopple** [comment]
that's a massive difference @soedirgo - great find. Let's definitely do that - I'll start a new issue
