### ISSUE TITLE
Don't run name updates on `/tables` and `/columns` if the name is not changed

### ISSUE THREAD

**Issue by kiwicopple** [supabase/pg-api#44]
This line:

https://github.com/supabase/pg-api/blob/f7d66c2395e682d4ebb082fe881fe1662052b5e2/src/api/tables.ts#L87

Should only run if the name is different from what the table was previously named. 

At the moment it is running even if you pass it the same name. This results in an error `relation already exists`.

**Comment by kiwicopple** [comment]
Looks like this affects the `/columns` api too

**Comment by soedirgo** [comment]
@joshenlim can you tell me how you're using the `PATCH`? All the fields in `PATCH` are optional, so the intended usage is to only specify fields you want to update.

**Comment by kiwicopple** [comment]
I don't think it should error when a users passes fields which havne't changed though Bobbie. Think of 2 users interacting with a system, one user has no idea what the other is changes. If we are throwing errors because user1 is trying to make an update that user2 has already made, it will be very confusing for user1
