### ISSUE TITLE
POST pg/columns throws 500

### ISSUE THREAD

**Issue by joshenlim** [supabase/pg-api#47]
This is the code that i'm using to poke the POST endpoint for columns

```
curl --location --request POST 'localhost:8000/pg/columns' \
--header 'x-connection-encrypted: U2FsdGVkX19kzsnMCPnxnFX52fPxwv6VFR3s3H4gvkDpDlJgf6wut+ylfvicB902wOcbLET39WTrvh4oUmip6xshgm3x39Rq3x1uUhGNPMLdediIPwKlScqA7aqjufNxmYttetfC6h8V93E5BpaOWtmOH06ty4JKdkeUYGpPoR0=' \
--header 'apikey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTU5NTQ3Njg3MiwiZXhwIjoyNTQyMTYxNjcyLCJhdWQiOiIiLCJzdWIiOiIiLCJyb2xlIjoicG9zdGdyZXMifQ.7wwVEyU4OFEWyoezDt6ud3cDQ-dbG3PlghGTCu8czz8' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
    "tableId": 16625,
    "name": "col_1",
    "type": "int4",
    "comment": "asd"
}'
```

**Comment by soedirgo** [comment]
Is this on `develop`? I recently changed all fields to be snake_case, so you'll need to use `table_id` instead of `tableId`.

**Comment by joshenlim** [comment]
Ahh okay, lemme pull in develop and try this again!

**Comment by joshenlim** [comment]
Okay just tested - alls good! Have written a helper function on the FE to parse all the payload to pg-api as snake case too. Thanks so much for the heads up Bobbie!

**Comment by joshenlim** [comment]
![image](https://user-images.githubusercontent.com/19742402/89774863-3ceceb80-db39-11ea-8876-74a120726141.png)

Quick thought though - perhaps the errors coming back from the API could be improved too, perhaps throw a 422 instead of a 500

**Comment by soedirgo** [comment]
> Quick thought though - perhaps the errors coming back from the API could be improved too, perhaps throw a 422 instead of a 500

Noted @joshenlim, I'm planning to turn pg-api into an API-first design, which is ongoing in #36. You'll be able to see the OpenAPI docs in https://supabase.github.io/pg-api (it's currently the old one) once it's merged, which includes error response information. I might need your feedback for polishing it. :)

Anyway, 500 would mean "it's not you, it's on us, please report this as a bug".
