### ISSUE TITLE
GET tables/id does not return the same structure as from GET tables

### ISSUE THREAD

**Issue by joshenlim** [supabase/pg-api#49]
Mainly missing columns key that i'll need on the FE

Return body from tables/id:
![image](https://user-images.githubusercontent.com/19742402/89878136-b9440500-dbf3-11ea-88b2-df6555d59810.png)

Return body from tables:
![image](https://user-images.githubusercontent.com/19742402/89878171-c3660380-dbf3-11ea-8a18-29220bf9d361.png)

**Comment by joshenlim** [comment]
POST tables also does not return the same structure as GET /tables, has same structure as GET tables/id

![image](https://user-images.githubusercontent.com/19742402/89878390-10e27080-dbf4-11ea-9a2a-913bdea0aab1.png)

**Comment by soedirgo** [comment]
👍 Good catch!
