### ISSUE TITLE
PATCH Column change type throws 500

### ISSUE THREAD

**Issue by joshenlim** [supabase/pg-api#50]
Not sure if this is intended but trying to update field type from text -> int4 throws a 500, but text -> varchar is okay
Similarly, trying to update int4 -> float8 is fine too, but int4 -> text throws 500

Are we limiting column type updates to only types that are similar to what it was originally?

**Comment by soedirgo** [comment]
Was the table in which the column belongs empty? I think the problem is if you update to an incompatible type, then the existing entries in that column becomes invalid.

**Comment by joshenlim** [comment]
Yeah i was trying to do the update for an empty table. I created an empty table, added a new column then tried to update the new column's type

**Comment by soedirgo** [comment]
OK, seems like it's not allowed even if it's an empty table. The solution is to use a `USING` clause at the end (like `USING some_column::int4` in your case), will update `/columns` soon.

**Comment by joshenlim** [comment]
Awesome, thanks so much! 👍
