### ISSUE TITLE
Updating of rows from tables with no primary key

### ISSUE THREAD

**Issue by joshenlim** [supabase/pg-api#52]
Currently the editor breaks if a user tries to update a row from a table with no primary key - wondering if there's an endpoint that I could use for this scenario?

Row updates on the editor is currently done via the supabase client

**Comment by soedirgo** [comment]
I don't think it makes sense to update a single row in a table without a PK. How do you know uniquely which row to update?

This looks like a big technical decision: we can have implicit Supabase-specific primary key, but then users can't have their own primary key. Or we can let users use their own primary key, but we can't do row-level updates on the table editor.

Perhaps @awalias & @kiwicopple want to chime in?

**Comment by kiwicopple** [comment]
Agreed with @soedirgo 

We shouldn't make decisions in `pg-api` on how to update rows without some sort of matching criteria specified by the request initiator.

DBeaver handles this by trying to match all the details of the row. We can do the same in our front end using PostgREST, or better yet - don't allow in and do a popup/wizard that guides the user to creating a PK on their table

Closing for now - feel free to open for more discussion

**Comment by joshenlim** [comment]
Gotcha on this, I'll throw in the popup about creating a PK when updating tables with no PK into V11 too
