### ISSUE TITLE
apostrophes not being escaped?

### ISSUE THREAD

**Issue by awalias** [supabase/pg-api#57]
@joshenlim mentioned that an apostrophe in sql comment caused pg-api to fail - need to verify that these are being escaped correctly else could be potential for sql injection attacks

**Comment by kiwicopple** [comment]
For context/replication - Joshen was saying that this is when he was trying to create a new table, and he added an apostrophe to the "comment".

**Comment by joshenlim** [comment]
I'll send a screenshot of the payload that i tried to send in later this evening

**Comment by soedirgo** [comment]
Relevant line:

https://github.com/supabase/pg-api/blob/1c10b942cddd47c90d5c3f82457a44868f1e1205/src/api/columns.ts#L129

I'll go about escaping this and going over other pg-api issues tonight.

**Comment by soedirgo** [comment]
I realized that most of pg-api's queries are in [DDL](https://en.wikipedia.org/wiki/Data_definition_language), so as recommended by node-postgres [here](https://node-postgres.com/features/queries#parameterized-query), I'll use pg-format for this, [which seems to work](https://jspm.org/sandbox#H4sIAAAAAAAAAz2RS4+CMBSF9/yKK4lBDQN7UTfGhYmPhc5uFpb2DtRQim1h9N9PH2JCw+W79xxO23wRwQLuuhNwIS0r5dN+O3StuQYdEOATaW9Qw+4CQrK+seXAydINurWaMEnNq0OojWg2HmmqeGfA0XUcRLHvAGRZZpw9Mm6kAioZWuRVeZAFi1Ky11uyYnwAztYxla0hvEUVb1a5hWOfknYgOoz40vVDFczyj5tbuztSG67Gzx7LF2guuuYFveZtBT7hnyJdh8ply6PItqUy8CuVIPalpICkNqbTyzx3R5gxHPKu+goDSRFFDRrQtEZBYA03AuWt8MyQskGPfkbUEhFINhIqhcDWOLhPBoRKWjMbzSofvXTXYaNDzGRvzeI3m9zG3z4aqwxRZsn2fDzuTlc4n2B7PnwfTzDdZ/6B/QWmhyJJ30HTEC71gdIxxLyI7Mlr2WDWyGpmzefFP+hguUs8AgAA).

We already use sql-template-strings, but it doesn't work for DDL. I'll see if I can replace it completely with just pg-format.

**Comment by soedirgo** [comment]
After digging into OpenAPI validators, I figured the tooling around OpenAPI/Postgres is more important than the language itself. Looking at https://openapi.tools, it all comes down to [tsoa](https://github.com/lukeautry/tsoa) or [LoopBack](https://github.com/strongloop/loopback-next) for TypeScript vs. [oapi-codegen](https://github.com/deepmap/oapi-codegen) for Go.

I think the TS/Node ecosystem wins out, and I couldn't find an alternative for pg-format for Go, and the statically-typed nature of Go is kinda moot since we're using a validator anyway.

**Comment by kiwicopple** [comment]
Great, thanks for the research @soedirgo - this will feed into the Supabase API decision too.

Also great to see decisions being made based on "best tool" principles rather than "fun to learn"

**Comment by kiwicopple** [comment]
Question: why `pg-format` over `sql-template-strings`, which we've already imported ?

I find this template strings much more readable, especially as the queries start getting lengthy

```js 
// pg-format
const commentSql = format('COMMENT ON COLUMN %I.%I.%I IS %L;', schema, table, name, comment)

// sql-template-strings
const commentSql = SQL`COMMENT ON COLUMN "${schema}"."${table}"."${name}" is "${comment}";`
```

[jsdev](https://jspm.org/sandbox#H4sIAAAAAAAAA3WQTWuEMBCG7/srpouLK2ike2zoaenB4gfF9taDWc26lsSoiQtF/O9NjB5KKQQSHmaeeTMN78Sg4CoGTvQ1CA7uTalOPoXhl+w4qug97OrAFrh419iG/C3+r1r2LFCUd4woGkg1NG0tdeOOUQWyvFFO4BkKApcCL0yRC6ML+txQS7glaCOl4Jy2ysDIvVOohZZps+7sR6GoBNJWsK/EqGX7lT0U29iePepW+4mje86S5CV9hyyFcxZ/JCkcIrQciHI4xNj116S+TecvifwthYc360lb9SqKv0ZnsoYZOdPiMA9jmc0MZ1pVM9YZS9FKwShioj6aqN5v9JpnKbKLbK7fpuKkA42M+XDyPPwDS07yHcMBAAA=)

**Comment by soedirgo** [comment]
sql-template-strings doesn't work when you pass that to node-postgres. Can't demonstrate through jspm unfortunately (can't import node-postgres).

**Comment by kiwicopple** [comment]
that's annoying :( 

> doesn't work

It throws some sort of error?

**Comment by soedirgo** [comment]
Yup, something like this:

```
PG Error
throwing error error: syntax error at or near "$1"
    at Connection.parseE (/Users/dan/work/pg-api/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/Users/dan/work/pg-api/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/Users/dan/work/pg-api/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '19',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1149',
  routine: 'scanner_yyerror'
}
```

Also, I don't think it handled `\` the way we wanted it to, there's no need to escape it within double quotes.

**Comment by kiwicopple** [comment]
Hard to tell from the error but it seems like this could be the culprit

![image](https://user-images.githubusercontent.com/10214025/92347596-27042380-f103-11ea-89fd-c1d09525532f.png)

It's a shame because I find the `%I.%I.%I IS %L` syntax developer-hostile. Let's ear-mark this one for later. If our goal is to make Postgres an amazing experience for developers, this seems like an area to revisit
