### ISSUE TITLE
Manage subscriptions

### ISSUE THREAD

**Issue by kiwicopple** [supabase/pg-api#65]
# Feature request

## Is your feature request related to a problem? Please describe.

The goal is to be able to manage subscriptions for 

## Describe the solution you'd like

- List subscriptions
- Enable replication for all tables
- Disable replication for all tables
- Enable for individual table (only if it's not "for all tables")
- Disable for individual table (only if it's not "for all tables")
- Enable replication type "FULL" for each table

Possible:

- Add replication status for each table to the `/tables` route

## Additional context

- Related (internal task) https://github.com/supabase/infrastructure/issues/193

**Comment by soedirgo** [comment]
Would making a new endpoint (`/publications`) be a good idea? Though realistically, we're only using `/pg/publications/supabase_realtime`.

**Comment by kiwicopple** [comment]
Yes I think it's a good idea. Even though we only use one, we could create several publication in the future (for replication)
