### ISSUE TITLE
live_count isn't always accurate

### ISSUE THREAD

**Issue by kiwicopple** [supabase/pg-api#66]
# Bug report

## Describe the bug

The live_count on tables is only indicative, but we are using it on the frontend to determine the number of rows. We should see if there is a figure that is accurate always

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. insert thousands of rows into a database
2. query `/tables`
3. check `live_count`

## Screenshots

<img width="533" alt="image" src="https://user-images.githubusercontent.com/10214025/95064915-f11e8300-0732-11eb-9850-48c8d9a7f802.png">

Don't worry about the error he mentions, but this is the Dashboard after he has inserted 20m rows:

![image](https://user-images.githubusercontent.com/10214025/95065117-30e56a80-0733-11eb-8d3b-0fdd1a0a4159.png)

**Comment by soedirgo** [comment]
Relevant SO thread: https://stackoverflow.com/questions/2596670/how-do-you-find-the-row-count-for-all-your-tables-in-postgres

I see 2 options:
- Stick with row count estimates, but run `ANALYZE` at some point (in FE, through `/query`? `pg-api`, in `GET /tables`?)
- Get exact count with `COUNT(*)`

Getting updated count estimates should be enough though. Thoughts?

**Comment by kiwicopple** [comment]
It's an interesting one - i think count(*) is a non-starter becuase it will be very expensive on large databases.

@steve-chavez I think PostgREST just brought out estimated counts in the headers right? What method is used to get accurate results?

**Comment by steve-chavez** [comment]
@kiwicopple The method basically is: when the rows are small enough(configurable threshold) we use the exact `count(*)` otherwise if the rows are big(threshold surpassed) we use the planner count. Discussion and more details at: https://github.com/PostgREST/postgrest/issues/1378#issuecomment-531506803.

**Comment by soedirgo** [comment]
DBeaver fetches the first 200 by default but lets you [manually trigger](https://github.com/dbeaver/dbeaver/wiki/Data-Editor) a count (I'm assuming exact count).

pgAdmin checks the count estimate (I think PostgREST uses `LIMIT` instead?), and it [only counts the rows](https://www.pgadmin.org/docs/pgadmin4/development/preferences.html) if the estimate is less than 2000 (configurable).

If we want to go with estimate counts, we should probably be more explicit that it's an estimate, not an exact count.

**Comment by kiwicopple** [comment]
Yeah I think you're right Bobbie - should we change it to be more explicit? Then we can let the developer decide how they choose to get more accurate counts.

For Supabase, we can add the same logic to the Dashboard - if it's less than 2000 we will call `count(*)`, and anything greater we can use the estimate
